export const brandColorMap: Record<string, string> = {
  'Business Flex': 'bg-red-600 text-white',
  'Business Classic': 'bg-orange-500 text-white',
  'Premium Flex': 'bg-green-600 text-white',
  'Premium Classic': 'bg-green-400 text-white',
  'Eco Flex': 'bg-green-500 text-white',
  'Eco Classic': 'bg-blue-500 text-white',
  'Eco Value': 'bg-gray-500 text-white',
  First: 'bg-purple-600 text-white',
  'ECONOMY CLASSIC': 'bg-green-500 text-white',
  'ECONOMY CONVENIENCE': 'bg-blue-500 text-white',
  'ECONOMY COMFORT': 'bg-orange-500 text-white',
  'Economy Light': 'bg-blue-500 text-white',
  'Economy Classic': 'bg-green-500 text-white',
  'Economy Classic Flex': 'bg-purple-600 text-white',
  'Economy Delight': 'bg-red-400 text-white',
  'Economy Delight Flex': 'bg-orange-500 text-white',
  Comfort: 'bg-blue-500 text-white',
  'Comfort Plus': 'bg-green-500 text-white',
  Flex: 'bg-purple-600 text-white',
  'Economy Basic': 'bg-blue-500 text-white',
  'Economy Value': 'bg-green-500 text-white',
  'Economy Comfort': 'bg-purple-600 text-white',
  'Economy Deluxe': 'bg-orange-500 text-white',
  'Economy Standard': 'bg-purple-600 text-white',
  'Economy Flexi': 'bg-red-400 text-white',
  'Economy Partially': 'bg-blue-500 text-white',
  'Economy Fully Ref': 'bg-purple-600 text-white',
  'Economy Saver': 'bg-blue-500 text-white',
  'Economy Green': 'bg-green-500 text-white',
  'Economy Base': 'bg-yellow-400 text-white',
  'Economy Flex': 'bg-red-400 text-white',
  'Economy Standard3': 'bg-purple-600 text-white',
  'Economy Flex1': 'bg-red-400 text-white',
  'Economy Full Flex': 'bg-red-600 text-white',

  'Premium Economy Saver': '',
  'Premium Economy Base': 'bg-blue-500 text-white',
  'Premium Economy Green': 'bg-green-500 text-white',
  'Premium Economy Flex': 'bg-red-400 text-white',
  'Premium Economy Saver Fully': '',
  'Premium Economy Saver Green': '',

  'Upper Class': 'bg-blue-500 text-white',
  'Upper Class Standard': 'bg-blue-500 text-white',
  'Upper Class Green': 'bg-green-500 text-white',
  'Upper Class Flexi': 'bg-red-400 text-white',
  'Upper Class Flex': 'bg-red-400 text-white',
  'Business Base': 'bg-blue-500 text-white',
  'Business Standard': 'bg-blue-500 text-white',
  'Business Green': 'bg-green-500 text-white',
  'Business Flexi': 'bg-red-400 text-white',
  'Business Light': 'bg-blue-500 text-white',
  'BUSINESS COMFORT': 'bg-green-500 text-white',
  'BUSINESS ELITE': 'bg-red-600 text-white',
  'Business Essential': 'bg-green-500 text-white',
};
