// List of airlines for filtering flights based on airline preference

export const airLines = [
  { code: 'Any', name: 'Any' },
  { code: 'AA', name: 'American Airlines' },
  { code: 'AC', name: 'Air Canada' },
  { code: 'AD', name: 'Azul Brazilian Airlines' },
  { code: 'AF', name: 'Air France' },
  { code: 'A3', name: 'Aegean Airlines' },
  { code: 'AI', name: 'Air India' },
  { code: 'AM', name: 'Aeromexico' },
  { code: 'AR', name: 'Aerolineas Argentinas' },
  { code: 'AS', name: 'Alaska Airlines' },
  { code: 'AT', name: 'Royal Air Maroc' },
  { code: 'AV', name: 'Avianca' },
  { code: 'AY', name: 'Finnair' },
  { code: 'AZ', name: 'ITA Airways' },
  { code: 'BA', name: 'British Airways' },
  { code: 'BI', name: 'Royal Brunei Airlines' },
  { code: 'BR', name: 'EVA Air' },
  { code: 'BT', name: 'Air Baltic' },
  { code: 'CA', name: 'Air China' },
  { code: 'CI', name: 'China Airlines' },
  { code: 'CM', name: 'Copa Airlines' },
  { code: 'CX', name: 'Cathay Pacific' },
  { code: 'CZ', name: 'China Southern Airlines' },
  { code: 'DL', name: 'Delta Air Lines' },
  { code: 'DY', name: 'Norwegian Air Shuttle' },
  { code: 'EK', name: 'Emirates' },
  { code: 'EI', name: 'Aer Lingus' },
  { code: 'ET', name: 'Ethiopian Airlines' },
  { code: 'EY', name: 'Etihad Airways' },
  { code: 'EW', name: 'Eurowings' },
  { code: 'F9', name: 'Frontier Airlines' },
  { code: 'FI', name: 'Icelandair' },
  { code: 'FZ', name: 'Flydubai' },
  { code: 'GA', name: 'Garuda Indonesia' },
  { code: 'G3', name: 'GOL Linhas Aéreas' },
  { code: 'GF', name: 'Gulf Air' },
  { code: 'GK', name: 'Jetstar Japan' },
  { code: 'HA', name: 'Hawaiian Airlines' },
  { code: 'HG', name: 'Niki' },
  { code: 'HM', name: 'Air Seychelles' },
  { code: 'HO', name: 'Juneyao Airlines' },
  { code: 'HU', name: 'Hainan Airlines' },
  { code: 'HX', name: 'Hong Kong Airlines' },
  { code: 'IB', name: 'Iberia' },
  { code: 'IX', name: 'Air India Express' },
  { code: 'JL', name: 'Japan Airlines' },
  { code: 'JQ', name: 'Jetstar Airways' },
  { code: 'JU', name: 'Air Serbia' },
  { code: 'KE', name: 'Korean Air' },
  { code: 'KL', name: 'KLM Royal Dutch Airlines' },
  { code: 'KQ', name: 'Kenya Airways' },
  { code: 'KU', name: 'Kuwait Airways' },
  { code: 'LA', name: 'LATAM Airlines' },
  { code: 'LG', name: 'Luxair' },
  { code: 'LH', name: 'Lufthansa' },
  { code: 'LO', name: 'LOT Polish Airlines' },
  { code: 'LP', name: 'LATAM Peru' },
  { code: 'LX', name: 'Swiss International Air Lines' },
  { code: 'LY', name: 'El Al Israel Airlines' },
  { code: 'ME', name: 'Middle East Airlines' },
  { code: 'MF', name: 'Xiamen Airlines' },
  { code: 'MH', name: 'Malaysia Airlines' },
  { code: 'MK', name: 'Air Mauritius' },
  { code: 'MS', name: 'Egyptair' },
  { code: 'MU', name: 'China Eastern Airlines' },
  { code: 'NH', name: 'All Nippon Airways' },
  { code: 'NZ', name: 'Air New Zealand' },
  { code: 'OA', name: 'Olympic Air' },
  { code: 'OD', name: 'Batik Air Malaysia' },
  { code: 'OK', name: 'Czech Airlines' },
  { code: 'OS', name: 'Austrian Airlines' },
  { code: 'OU', name: 'Croatia Airlines' },
  { code: 'OZ', name: 'Asiana Airlines' },
  { code: 'PC', name: 'Pegasus Airlines' },
  { code: 'PG', name: 'Bangkok Airways' },
  { code: 'PK', name: 'Pakistan International Airlines' },
  { code: 'PR', name: 'Philippine Airlines' },
  { code: 'PS', name: 'Ukraine International Airlines' },
  { code: 'PW', name: 'Precision Air' },
  { code: 'PZ', name: 'LATAM Paraguay' },
  { code: 'QR', name: 'Qatar Airways' },
  { code: 'QF', name: 'Qantas' },
  { code: 'RJ', name: 'Royal Jordanian' },
  { code: 'RO', name: 'TAROM' },
  { code: 'RS', name: 'Air Seoul' },
  { code: 'S7', name: 'S7 Airlines' },
  { code: 'SA', name: 'South African Airways' },
  { code: 'SB', name: 'Aircalin' },
  { code: 'SK', name: 'Scandinavian Airlines' },
  { code: 'SN', name: 'Brussels Airlines' },
  { code: 'SQ', name: 'Singapore Airlines' },
  { code: 'SV', name: 'Saudia' },
  { code: 'SW', name: 'Air Namibia' },
  { code: 'SY', name: 'Sun Country Airlines' },
  { code: 'TA', name: 'TACA Airlines' },
  { code: 'TG', name: 'Thai Airways' },
  { code: 'TK', name: 'Turkish Airlines' },
  { code: 'TP', name: 'TAP Air Portugal' },
  { code: 'TU', name: 'Tunisair' },
  { code: 'TX', name: 'Air Caraïbes' },
  { code: 'UA', name: 'United Airlines' },
  { code: 'UL', name: 'SriLankan Airlines' },
  { code: 'UX', name: 'Air Europa' },
  { code: 'VA', name: 'Virgin Australia' },
  { code: 'VN', name: 'Vietnam Airlines' },
  { code: 'VS', name: 'Virgin Atlantic' },
  { code: 'VX', name: 'Virgin America' },
  { code: 'VY', name: 'Vueling' },
  { code: 'WA', name: 'KLM Cityhopper' },
  { code: 'WB', name: 'RwandAir' },
  { code: 'W6', name: 'Wizz Air' },
  { code: 'WF', name: 'Widerøe' },
  { code: 'WN', name: 'Southwest Airlines' },
  { code: 'WS', name: 'WestJet' },
  { code: 'WY', name: 'Oman Air' },
  { code: 'X3', name: 'TUIfly' },
  { code: 'XL', name: 'LATAM Ecuador' },
  { code: 'XY', name: 'flynas' },
  { code: 'YE', name: 'Yemenia' },
  { code: 'ZB', name: 'Monarch Airlines' },
  { code: 'ZL', name: 'Regional Express (REX)' },
  { code: 'Z8', name: 'Amaszonas' },
];

// Time options for filtering flights based on departure and arrival times

export const timeOptions = [
  {
    label: 'Before 6 AM',
    value: { start: '00:00:00', end: '06:00:00' },
    icon: '🌙',
  },
  {
    label: '6 AM - 12 PM',
    value: { start: '06:00:00', end: '12:00:00' },
    icon: '☀️',
  },
  {
    label: '12 PM - 6 PM',
    value: { start: '12:00:00', end: '18:00:00' },
    icon: '🌤️',
  },
  {
    label: 'After 6 PM',
    value: { start: '18:00:00', end: '24:00:00' },
    icon: '🌙',
  },
];
